export const NUTRIENTS = [
  {
    id: "3605ea0f-b57a-4e7b-9478-a00453640fa8",
    code: "energy_kcal",
    nameUa: "Енергія",
    nameEn: "Energy",
    group: "ENERGY",
    unit: "KCAL",
    displayLevel: "BASIC",
    isTargetable: true,
    sortOrder: 10,
    usdaNutrientId: 1008,
    usdaNutrientNumber: "208",
    isActive: true,
  },
  {
    id: "28bf5260-7362-4949-8d22-ac9d26f94e6d",
    code: "protein",
    nameUa: "Білки",
    nameEn: "Protein",
    group: "MACRONUTRIENT",
    unit: "G",
    displayLevel: "BASIC",
    isTargetable: true,
    sortOrder: 20,
    usdaNutrientId: 1003,
    usdaNutrientNumber: "203",
    isActive: true,
  },
  {
    id: "69e6a1fa-743b-4bc8-8647-e39a4f7a4fb2",
    code: "total_fat",
    nameUa: "Жири",
    nameEn: "Total fat",
    group: "MACRONUTRIENT",
    unit: "G",
    displayLevel: "BASIC",
    isTargetable: true,
    sortOrder: 30,
    usdaNutrientId: 1004,
    usdaNutrientNumber: "204",
    isActive: true,
  },
  {
    id: "00dc8994-28a7-4169-a0f1-b6d62928f262",
    code: "saturated_fat",
    nameUa: "Насичені жири",
    nameEn: "Saturated fat",
    group: "FATTY_ACID",
    unit: "G",
    displayLevel: "BASIC",
    isTargetable: true,
    sortOrder: 40,
    usdaNutrientId: 1258,
    usdaNutrientNumber: "606",
    isActive: true,
  },
  {
    id: "7a288020-b1cb-48c6-b5c6-b3155933bc93",
    code: "monounsaturated_fat",
    nameUa: "Мононенасичені жири",
    nameEn: "Monounsaturated fat",
    group: "FATTY_ACID",
    unit: "G",
    displayLevel: "EXTENDED",
    isTargetable: false,
    sortOrder: 50,
    usdaNutrientId: 1292,
    usdaNutrientNumber: "645",
    isActive: true,
  },
  {
    id: "ebc858de-2703-4cf8-8f53-7ad9028ec0ee",
    code: "polyunsaturated_fat",
    nameUa: "Поліненасичені жири",
    nameEn: "Polyunsaturated fat",
    group: "FATTY_ACID",
    unit: "G",
    displayLevel: "EXTENDED",
    isTargetable: false,
    sortOrder: 60,
    usdaNutrientId: 1293,
    usdaNutrientNumber: "646",
    isActive: true,
  },
  {
    id: "e7b983d7-cf7d-4ba4-90b5-fb1df929e249",
    code: "trans_fat",
    nameUa: "Трансжири",
    nameEn: "Trans fat",
    group: "FATTY_ACID",
    unit: "G",
    displayLevel: "BASIC",
    isTargetable: true,
    sortOrder: 70,
    usdaNutrientId: 1257,
    usdaNutrientNumber: "605",
    isActive: true,
  },
  {
    id: "6381aa40-46d5-45d6-97d0-3c12ff722ece",
    code: "carbohydrate",
    nameUa: "Вуглеводи",
    nameEn: "Carbohydrate",
    group: "MACRONUTRIENT",
    unit: "G",
    displayLevel: "BASIC",
    isTargetable: true,
    sortOrder: 80,
    usdaNutrientId: 1005,
    usdaNutrientNumber: "205",
    isActive: true,
  },
  {
    id: "3cd651bf-b67e-40f1-a4ad-448cae15c5aa",
    code: "total_sugars",
    nameUa: "Цукри",
    nameEn: "Total sugars",
    group: "MACRONUTRIENT",
    unit: "G",
    displayLevel: "BASIC",
    isTargetable: true,
    sortOrder: 90,
    usdaNutrientId: 2000,
    usdaNutrientNumber: "269",
    isActive: true,
  },
  {
    id: "cda3f401-c5cc-4393-bd3a-f91959f5f340",
    code: "dietary_fiber",
    nameUa: "Клітковина",
    nameEn: "Dietary fiber",
    group: "MACRONUTRIENT",
    unit: "G",
    displayLevel: "BASIC",
    isTargetable: true,
    sortOrder: 100,
    usdaNutrientId: 1079,
    usdaNutrientNumber: "291",
    isActive: true,
  },
  {
    id: "452380f3-7208-452d-80bf-8f72984fe6ef",
    code: "cholesterol",
    nameUa: "Холестерин",
    nameEn: "Cholesterol",
    group: "OTHER",
    unit: "MG",
    displayLevel: "BASIC",
    isTargetable: true,
    sortOrder: 110,
    usdaNutrientId: 1253,
    usdaNutrientNumber: "601",
    isActive: true,
  },
  {
    id: "0acbbd96-de4d-4b45-8441-81ca437d2dd4",
    code: "sodium",
    nameUa: "Натрій",
    nameEn: "Sodium",
    group: "MINERAL",
    unit: "MG",
    displayLevel: "BASIC",
    isTargetable: true,
    sortOrder: 120,
    usdaNutrientId: 1093,
    usdaNutrientNumber: "307",
    isActive: true,
  },
  {
    id: "87637246-138b-4dd6-b27b-e3382b761436",
    code: "potassium",
    nameUa: "Калій",
    nameEn: "Potassium",
    group: "MINERAL",
    unit: "MG",
    displayLevel: "BASIC",
    isTargetable: true,
    sortOrder: 130,
    usdaNutrientId: 1092,
    usdaNutrientNumber: "306",
    isActive: true,
  },
  {
    id: "72a1f5fd-1f40-4330-af89-a5b6399959d8",
    code: "calcium",
    nameUa: "Кальцій",
    nameEn: "Calcium",
    group: "MINERAL",
    unit: "MG",
    displayLevel: "BASIC",
    isTargetable: true,
    sortOrder: 140,
    usdaNutrientId: 1087,
    usdaNutrientNumber: "301",
    isActive: true,
  },
  {
    id: "178c114e-be3c-4aa4-846f-ea13c6ff8ebb",
    code: "iron",
    nameUa: "Залізо",
    nameEn: "Iron",
    group: "MINERAL",
    unit: "MG",
    displayLevel: "BASIC",
    isTargetable: true,
    sortOrder: 150,
    usdaNutrientId: 1089,
    usdaNutrientNumber: "303",
    isActive: true,
  },
  {
    id: "e0ea375e-6040-48c5-851c-168c32648f5e",
    code: "magnesium",
    nameUa: "Магній",
    nameEn: "Magnesium",
    group: "MINERAL",
    unit: "MG",
    displayLevel: "EXTENDED",
    isTargetable: true,
    sortOrder: 160,
    usdaNutrientId: 1090,
    usdaNutrientNumber: "304",
    isActive: true,
  },
  {
    id: "d5cf9be0-ff0c-4d0f-9741-4b30a728918f",
    code: "phosphorus",
    nameUa: "Фосфор",
    nameEn: "Phosphorus",
    group: "MINERAL",
    unit: "MG",
    displayLevel: "EXTENDED",
    isTargetable: false,
    sortOrder: 170,
    usdaNutrientId: 1091,
    usdaNutrientNumber: "305",
    isActive: true,
  },
  {
    id: "3713b523-4ac5-45da-80e6-39c5780c588b",
    code: "zinc",
    nameUa: "Цинк",
    nameEn: "Zinc",
    group: "MINERAL",
    unit: "MG",
    displayLevel: "EXTENDED",
    isTargetable: true,
    sortOrder: 180,
    usdaNutrientId: 1095,
    usdaNutrientNumber: "309",
    isActive: true,
  },
  {
    id: "29100bb7-5b6e-4f7b-9500-854c6fbefa72",
    code: "selenium",
    nameUa: "Селен",
    nameEn: "Selenium",
    group: "MINERAL",
    unit: "MCG",
    displayLevel: "EXTENDED",
    isTargetable: true,
    sortOrder: 190,
    usdaNutrientId: 1103,
    usdaNutrientNumber: "317",
    isActive: true,
  },
  {
    id: "d03b48d4-a683-4f13-9e23-885bdfd590f8",
    code: "iodine",
    nameUa: "Йод",
    nameEn: "Iodine",
    group: "MINERAL",
    unit: "MCG",
    displayLevel: "EXTENDED",
    isTargetable: true,
    sortOrder: 200,
    usdaNutrientId: 1100,
    usdaNutrientNumber: "314",
    isActive: true,
  },
  {
    id: "9bec5bbe-3f96-44a4-b2b3-7125534344f4",
    code: "vitamin_a_rae",
    nameUa: "Вітамін A (RAE)",
    nameEn: "Vitamin A (RAE)",
    group: "VITAMIN",
    unit: "MCG",
    displayLevel: "EXTENDED",
    isTargetable: true,
    sortOrder: 210,
    usdaNutrientId: 1106,
    usdaNutrientNumber: "320",
    isActive: true,
  },
  {
    id: "ec328fd9-1cff-486b-9276-f916a1b68d25",
    code: "vitamin_c",
    nameUa: "Вітамін C",
    nameEn: "Vitamin C",
    group: "VITAMIN",
    unit: "MG",
    displayLevel: "EXTENDED",
    isTargetable: true,
    sortOrder: 220,
    usdaNutrientId: 1162,
    usdaNutrientNumber: "401",
    isActive: true,
  },
  {
    id: "cd589ab8-dd0f-4157-9540-3a1280f71757",
    code: "vitamin_d",
    nameUa: "Вітамін D",
    nameEn: "Vitamin D",
    group: "VITAMIN",
    unit: "MCG",
    displayLevel: "BASIC",
    isTargetable: true,
    sortOrder: 230,
    usdaNutrientId: 1114,
    usdaNutrientNumber: "328",
    isActive: true,
  },
  {
    id: "8edace1e-67b6-4506-b18e-69ec821ef954",
    code: "vitamin_e",
    nameUa: "Вітамін E",
    nameEn: "Vitamin E",
    group: "VITAMIN",
    unit: "MG",
    displayLevel: "EXTENDED",
    isTargetable: true,
    sortOrder: 240,
    usdaNutrientId: 1109,
    usdaNutrientNumber: "323",
    isActive: true,
  },
  {
    id: "03ff5e99-6015-4d52-aa85-99a2421d64c3",
    code: "vitamin_k",
    nameUa: "Вітамін K",
    nameEn: "Vitamin K",
    group: "VITAMIN",
    unit: "MCG",
    displayLevel: "EXTENDED",
    isTargetable: true,
    sortOrder: 250,
    usdaNutrientId: 1185,
    usdaNutrientNumber: "430",
    isActive: true,
  },
  {
    id: "1399a308-9a01-4dbf-af36-3be8f6ace5b3",
    code: "thiamin",
    nameUa: "Тіамін (B1)",
    nameEn: "Thiamin (B1)",
    group: "VITAMIN",
    unit: "MG",
    displayLevel: "EXTENDED",
    isTargetable: true,
    sortOrder: 260,
    usdaNutrientId: 1165,
    usdaNutrientNumber: "404",
    isActive: true,
  },
  {
    id: "c8d8e1f6-6716-423c-b30a-65a500a5c7db",
    code: "riboflavin",
    nameUa: "Рибофлавін (B2)",
    nameEn: "Riboflavin (B2)",
    group: "VITAMIN",
    unit: "MG",
    displayLevel: "EXTENDED",
    isTargetable: true,
    sortOrder: 270,
    usdaNutrientId: 1166,
    usdaNutrientNumber: "405",
    isActive: true,
  },
  {
    id: "e07d809d-f149-44bc-ac8b-09784d99de6d",
    code: "niacin",
    nameUa: "Ніацин (B3)",
    nameEn: "Niacin (B3)",
    group: "VITAMIN",
    unit: "MG",
    displayLevel: "EXTENDED",
    isTargetable: true,
    sortOrder: 280,
    usdaNutrientId: 1167,
    usdaNutrientNumber: "406",
    isActive: true,
  },
  {
    id: "5eb9a955-ca8b-4067-9bce-c047312c2770",
    code: "vitamin_b6",
    nameUa: "Вітамін B6",
    nameEn: "Vitamin B6",
    group: "VITAMIN",
    unit: "MG",
    displayLevel: "EXTENDED",
    isTargetable: true,
    sortOrder: 290,
    usdaNutrientId: 1175,
    usdaNutrientNumber: "415",
    isActive: true,
  },
  {
    id: "61944f2f-8bc9-4b74-90c5-1aa0ced042a3",
    code: "folate_total",
    nameUa: "Фолат загальний (B9)",
    nameEn: "Folate, total (B9)",
    group: "VITAMIN",
    unit: "MCG",
    displayLevel: "EXTENDED",
    isTargetable: false,
    sortOrder: 300,
    usdaNutrientId: 1177,
    usdaNutrientNumber: "417",
    isActive: true,
  },
  {
    id: "41c6770d-120f-4e26-98af-758d9c8651af",
    code: "folate_dfe",
    nameUa: "Фолат DFE (B9)",
    nameEn: "Folate, DFE (B9)",
    group: "VITAMIN",
    unit: "MCG",
    displayLevel: "EXTENDED",
    isTargetable: true,
    sortOrder: 310,
    usdaNutrientId: 1190,
    usdaNutrientNumber: "435",
    isActive: true,
  },
  {
    id: "da933139-564a-447b-b23d-4d9ff274de03",
    code: "vitamin_b12",
    nameUa: "Вітамін B12",
    nameEn: "Vitamin B12",
    group: "VITAMIN",
    unit: "MCG",
    displayLevel: "EXTENDED",
    isTargetable: true,
    sortOrder: 320,
    usdaNutrientId: 1178,
    usdaNutrientNumber: "418",
    isActive: true,
  },
  {
    id: "f95cbea1-6e3a-4768-84b1-9092a755dd6d",
    code: "choline",
    nameUa: "Холін",
    nameEn: "Choline",
    group: "OTHER",
    unit: "MG",
    displayLevel: "EXTENDED",
    isTargetable: true,
    sortOrder: 330,
    usdaNutrientId: 1180,
    usdaNutrientNumber: "421",
    isActive: true,
  },
  {
    id: "622a35e4-b362-4549-b111-834b5d23e747",
    code: "omega_3_ala",
    nameUa: "Омега-3 ALA",
    nameEn: "Omega-3 ALA",
    group: "FATTY_ACID",
    unit: "G",
    displayLevel: "EXTENDED",
    isTargetable: true,
    sortOrder: 340,
    usdaNutrientId: 1404,
    usdaNutrientNumber: "851",
    isActive: true,
  },
  {
    id: "6b68bcf8-9427-4541-8157-a560eecb5f87",
    code: "omega_3_epa",
    nameUa: "Омега-3 EPA",
    nameEn: "Omega-3 EPA",
    group: "FATTY_ACID",
    unit: "G",
    displayLevel: "EXTENDED",
    isTargetable: true,
    sortOrder: 350,
    usdaNutrientId: 1278,
    usdaNutrientNumber: "629",
    isActive: true,
  },
  {
    id: "e3653b27-b18d-42d7-ad7d-08685963a317",
    code: "omega_3_dha",
    nameUa: "Омега-3 DHA",
    nameEn: "Omega-3 DHA",
    group: "FATTY_ACID",
    unit: "G",
    displayLevel: "EXTENDED",
    isTargetable: true,
    sortOrder: 360,
    usdaNutrientId: 1272,
    usdaNutrientNumber: "621",
    isActive: true,
  },
] as const;
